package com.workmotion.domain;


public enum EmployeeEvents {
	APPROVE_ADDED, APPROVE_WORK_PERMIT ,APPROVE_SEC_CHECK, FINAL_APPROVE,
	REJECT_ADDED, REJECT_WORK_PERMIT ,REJECT_SEC_CHECK, FINAL_REJECT
}
